add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜ ](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✖ ](bold red)"

[cmd_duration]
min_time = 0
format = "took [$duration](bold yellow)"

[directory]
truncate_to_repo = false

[python]
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[shell]
fish_indicator = " "
powershell_indicator = "_"
disabled = false

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
